CREATE TABLE [dbo].[AssetManager_Hardware]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[HardwareAssetNumber] INT NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
    [AssetTag] NVARCHAR(6) NOT NULL, 
    [TypeId] INT NOT NULL, 
    [ModelId] INT NOT NULL, 
    [LocationId] INT NOT NULL, 
    [SerialNumber] NVARCHAR(100) NOT NULL, 
    [StatusId] INT NOT NULL, 
    [DisposalDate] DATETIME2(0) NULL, 
    [DepartmentId] INT NULL, 
    [AssignedToId] INT NULL, 
    [PurchaseOrderNumber] NVARCHAR(100) NOT NULL, 
    [Notes] NVARCHAR(MAX) NULL, 
    [PurchasedFromId] INT NOT NULL, 
    [SupportedById] INT NULL, 
    [DateOfPurchase] DATETIME2(0) NOT NULL, 
    [EndOfLifeDate] DATETIME2(0) NULL, 
    [DisposalMethodCode] INT NULL, 
    [ReassignedDate] DATETIME2(0) NULL, 
    [OldLocationId] INT NULL, 
    [OldAssignedToId] INT NULL, 
    [DeskRoomNumber] INT NULL, 
    [IPAddress] NVARCHAR(12) NULL, 
    [ComputerName] NVARCHAR(15) NULL,
	[CreatedDate] DATETIME2(0) NOT NULL, 
    [CreatedById] INT NOT NULL, 
    [ModifiedDate] DATETIME2(0) NULL, 
    [ModifiedById] INT NULL,
	CONSTRAINT [FK_AssetManager_Hardware_TypeId_ToAssetManager_Hardware_AssetType] FOREIGN KEY ([TypeId]) REFERENCES [AssetManager_Hardware_AssetType]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_ModelId_ToAssetManager_Models] FOREIGN KEY ([ModelId]) REFERENCES [AssetManager_Models]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_LocationId_ToNSLocations] FOREIGN KEY ([LocationId]) REFERENCES [NSLocations]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_StatusId_ToAssetManager_AssetStatus] FOREIGN KEY ([StatusId]) REFERENCES [AssetManager_AssetStatus]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_DepartmentId_ToDepartments] FOREIGN KEY ([DepartmentId]) REFERENCES [Departments]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_AssignedToId_ToServiceDesk_Users] FOREIGN KEY ([AssignedToId]) REFERENCES [ServiceDesk_Users]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_PurchasedFromId_ToAssetManager_Companies] FOREIGN KEY ([PurchasedFromId]) REFERENCES [AssetManager_Companies]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_SupportedById_ToAssetManager_Companies] FOREIGN KEY ([SupportedById]) REFERENCES [AssetManager_Companies]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_OldLocationId_ToNSLocations] FOREIGN KEY ([OldLocationId]) REFERENCES [NSLocations]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_OldAssignedToId_ToAssetManager_Users] FOREIGN KEY ([OldAssignedToId]) REFERENCES [ServiceDesk_Users]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_CreatedById_ToServiceDesk_Users_Id] FOREIGN KEY ([CreatedById]) REFERENCES [ServiceDesk_Users]([Id]),
	CONSTRAINT [FK_AssetManager_Hardware_ModifiedById_ToServiceDesk_Users_Id] FOREIGN KEY ([ModifiedById]) REFERENCES [ServiceDesk_Users]([Id])
)
